from __future__ import annotations

import json
import os
import subprocess
import sys
import time
from datetime import datetime, timezone
from pathlib import Path


def _env_flags(agent: str) -> list[str]:
    flags: list[str] = []
    if agent == "codex" and os.environ.get("OPENAI_API_KEY"):
        flags += ["-e", "OPENAI_API_KEY"]
    if agent == "claude" and os.environ.get("ANTHROPIC_API_KEY"):
        flags += ["-e", "ANTHROPIC_API_KEY"]
    return flags


def _agent_command(agent: str) -> str:
    if agent == "codex":
        return _logged_agent_command(
            agent="codex",
            invocation='codex exec --sandbox workspace-write --ask-for-approval never "$(cat prompt.md)"',
            log_path="_logs/codex.log",
        )
    if agent == "claude":
        return _logged_agent_command(
            agent="claude",
            invocation='claude -p --permission-mode bypassPermissions --output-format stream-json "$(cat prompt.md)"',
            log_path="_logs/claude.jsonl",
        )
    if agent == "shell-smoke":
        return (
            "mkdir -p submit _logs "
            "&& printf '%s\\n' '# Run History' '' '- Agent: shell-smoke' "
            "'- Created a synthetic one-second black MP4 for runner smoke testing.' "
            "'- Wrote submit/output.mp4 and submit/edit_decision.json.' "
            "'- This is not a task-solving edit.' > submit/run_history.md "
            "&& printf '%s\\n' '# Agent Transcript' '' "
            "'shell-smoke executed deterministic ffmpeg and printf commands only.' "
            "'No interactive agent transcript exists for this smoke run.' > submit/agent_transcript.md "
            "&& "
            "ffmpeg -y -f lavfi -i color=c=black:s=320x180:d=1 "
            "-f lavfi -i anullsrc=channel_layout=stereo:sample_rate=44100 "
            "-shortest -c:v libx264 -pix_fmt yuv420p -c:a aac submit/output.mp4 "
            "&& printf '{\"operations\": [], \"tools_used\": [\"smoke\", \"ffmpeg\"]}\\n' "
            "> submit/edit_decision.json "
            "&& echo 'smoke submission created'"
        )
    raise ValueError(f"Unsupported docker agent: {agent}")


def _logged_agent_command(*, agent: str, invocation: str, log_path: str) -> str:
    native_session_capture = _native_session_capture_command(agent)
    return f"""set -o pipefail
mkdir -p submit _logs
{invocation} 2>&1 | tee {log_path}
rc=${{PIPESTATUS[0]}}
{native_session_capture}
if [ ! -s submit/agent_transcript.md ]; then
  {{
    printf '%s\\n' '# Agent Transcript' ''
    printf '%s\\n' 'Raw CLI transcript is saved at `{log_path}`.'
    printf '%s\\n' 'Native agent session files, when available, are saved under `_logs/native_sessions/{agent}/`.'
    printf '%s\\n' 'This fallback file was generated by the benchmark runner because the agent did not create `submit/agent_transcript.md`.'
    printf '%s\\n' '' '## Tail Excerpt' '' '```text'
    tail -n 200 {log_path} 2>/dev/null || true
    printf '%s\\n' '' '```'
  }} > submit/agent_transcript.md
fi
if [ ! -s submit/run_history.md ]; then
  {{
    printf '%s\\n' '# Run History' ''
    printf '%s\\n' '- Agent: {agent}'
    printf '%s\\n' '- Executed prompt.md inside the benchmark sandbox.'
    printf '%s\\n' '- Raw transcript: {log_path}'
    printf '%s\\n' '- Native session snapshot: _logs/native_sessions/{agent}/'
    printf '%s\\n' "- Return code: $rc"
    printf '%s\\n' '' 'The agent did not provide a detailed run history, so this is a runner-generated fallback.'
  }} > submit/run_history.md
fi
exit "$rc"
"""


def _native_session_capture_command(agent: str) -> str:
    if agent == "codex":
        return """
native_dir="_logs/native_sessions/codex"
mkdir -p "$native_dir"
if [ -d "$HOME/.codex/sessions" ]; then
  cp -a "$HOME/.codex/sessions" "$native_dir/"
fi
if [ -f "$HOME/.codex/history.jsonl" ]; then
  cp -p "$HOME/.codex/history.jsonl" "$native_dir/history.jsonl"
fi
{
  printf '%s\\n' 'agent=codex'
  printf 'captured_at_utc='
  date -u +%Y-%m-%dT%H:%M:%SZ
  printf 'home=%s\\n' "$HOME"
  printf '%s\\n' 'expected_sources=$HOME/.codex/sessions,$HOME/.codex/history.jsonl'
  printf '%s\\n' 'saved_files:'
  find "$native_dir" -type f -print | sort
} > "$native_dir/session_manifest.txt"
"""
    if agent == "claude":
        return """
native_dir="_logs/native_sessions/claude"
mkdir -p "$native_dir"
if [ -d "$HOME/.claude/projects" ]; then
  cp -a "$HOME/.claude/projects" "$native_dir/"
fi
if [ -d "$HOME/.claude/sessions" ]; then
  cp -a "$HOME/.claude/sessions" "$native_dir/"
fi
{
  printf '%s\\n' 'agent=claude'
  printf 'captured_at_utc='
  date -u +%Y-%m-%dT%H:%M:%SZ
  printf 'home=%s\\n' "$HOME"
  printf '%s\\n' 'expected_sources=$HOME/.claude/projects,$HOME/.claude/sessions'
  printf '%s\\n' 'saved_files:'
  find "$native_dir" -type f -print | sort
} > "$native_dir/session_manifest.txt"
"""
    return ""


def _utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _write_json(path: Path, data: dict[str, object]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n")


def run_in_docker(
    *,
    agent: str,
    workspace: Path,
    image: str,
    cpus: str = "8",
    memory: str = "16g",
    network: str = "bridge",
) -> int:
    workspace = workspace.resolve()
    logs_dir = workspace / "_logs"
    logs_dir.mkdir(parents=True, exist_ok=True)
    cmd = [
        "docker",
        "run",
        "--rm",
        "--network",
        network,
        "--cpus",
        cpus,
        "--memory",
        memory,
        "-v",
        f"{workspace}:/workspace",
        "-w",
        "/workspace",
        *_env_flags(agent),
        image,
        "bash",
        "-lc",
        _agent_command(agent),
    ]
    started_at = _utc_now()
    start_time = time.monotonic()
    _write_json(
        logs_dir / "runner_command.json",
        {
            "agent": agent,
            "image": image,
            "cpus": cpus,
            "memory": memory,
            "network": network,
            "workspace": str(workspace),
            "started_at": started_at,
            "docker_command": cmd,
        },
    )

    log_path = logs_dir / "docker_stdout_stderr.log"
    returncode = 1
    error: str | None = None
    try:
        with log_path.open("w") as log_file:
            process = subprocess.Popen(  # noqa: S603
                cmd,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                text=True,
                bufsize=1,
            )
            assert process.stdout is not None
            for line in process.stdout:
                log_file.write(line)
                log_file.flush()
                sys.stdout.write(line)
                sys.stdout.flush()
            returncode = process.wait()
    except Exception as exc:  # noqa: BLE001
        error = str(exc)
        returncode = 1
    finally:
        ended_at = _utc_now()
        _write_json(
            logs_dir / "runner_result.json",
            {
                "agent": agent,
                "image": image,
                "started_at": started_at,
                "ended_at": ended_at,
                "duration_sec": round(time.monotonic() - start_time, 3),
                "returncode": returncode,
                "stdout_stderr_log": str(log_path),
                "error": error,
            },
        )
    return returncode
